---
version: 2
before:
  hooks:
    - go mod download
env:
  - CGO_ENABLED=1
builds:
  - id: amd64
    main: cmd/powervault_me5_exporter/main.go
    env:
      - CC=x86_64-linux-gnu-gcc
    goos:
      - linux
    goarch:
      - amd64
    ldflags:
      - -extldflags "-static"
      - -X github.com/prometheus/common/version.Version={{.Version}}
      - -X github.com/prometheus/common/version.Revision={{.FullCommit}}
      - -X github.com/prometheus/common/version.Branch={{.Branch}}
      - -X github.com/prometheus/common/version.BuildUser=goreleaser
      - -X github.com/prometheus/common/version.BuildDate={{.Date}}
archives:
  - id: archive
    builds:
      - amd64
    files:
      - LICENSE
      - CHANGELOG.md
    name_template: "prometheus-powervault-me5-exporter-{{ .Version }}.{{ .Os }}-{{ .Arch }}"
    wrap_in_directory: true
checksum:
  name_template: 'checksums.txt'
release:
  prerelease: auto
changelog:
  sort: asc
