{
 "title": "Dell PowerVault ME5",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "disk_group",
    "label": "Disk Group",
    "query": {
     "query": "label_values(me5_disk_group_info,name)"
    }
   },
   {
    "name": "host",
    "label": "Host",
    "query": {
     "query": "label_values(me5_system_info,host)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "System Health",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "me5_system_health{host=\"$host\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Last Scrape",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "me5_scrape_success{host=\"$host\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Redundancy Mode",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 5, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "me5_system_redundancy_mode{host=\"$host\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Service Tag",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "me5_service_tag_info{host=\"$host\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Last Scrape Time",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 11, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "me5_scrape_duration_seconds{host=\"$host\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Unacknowledged Alerts",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 14, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "me5_alerts_by_severity{host=\"$host\", acknowledged!=\"Yes\"} or vector(0)",
     "legendFormat": "{{severity}}"
    }
   ]
  },
  {
   "title": "Redundancy",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 3, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "me5_system_redundancy_status{host=\"$host\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 5, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "me5_controller_power_on_seconds_total{host=\"$host\"}",
     "legendFormat": "{{id}}"
    }
   ]
  },
  {
   "title": "Total Disks",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 8, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(me5_disk_info{host=\"$host\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Firmware Version",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 11, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "me5_firmware_bundle_info{status_name=\"Active\", host=\"$host\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Controllers and Throughput", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Controller CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "me5_controller_cpu_load_percent{host=\"$host\"}",
     "legendFormat": "{{id}}"
    }
   ]
  },
  {
   "title": "Controller Write Cache Used",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 9, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "me5_controller_write_cache_used_percent{host=\"$host\"}",
     "legendFormat": "{{id}}"
    }
   ]
  },
  {
   "title": "Controller Read Cache Hit Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "rate(me5_controller_read_cache_hits_total{host=\"$host\"}[5m]) / (rate(me5_controller_read_cache_hits_total{host=\"$host\"}[5m]) + rate(me5_controller_read_cache_misses_total{host=\"$host\"}[5m])) > 0",
     "legendFormat": "{{id}}"
    }
   ]
  },
  {
   "title": "Controller Write Cache Hit Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 9, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "rate(me5_controller_write_cache_hits_total{host=\"$host\"}[5m]) / (rate(me5_controller_write_cache_hits_total{host=\"$host\"}[5m]) + rate(me5_controller_write_cache_misses_total{host=\"$host\"}[5m])) > 0",
     "legendFormat": "{{id}}"
    }
   ]
  },
  {
   "title": "Controller Throughput",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "me5_controller_bytes_per_second{host=\"$host\"}",
     "legendFormat": "{{id}}"
    }
   ]
  },
  {
   "title": "Host Port Throughput",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "me5_host_port_bytes_per_second{host=\"$host\"} > 0",
     "legendFormat": "{{port}}"
    }
   ]
  },
  {
   "title": "IOPS",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "me5_host_port_iops{host=\"$host\"} > 0",
     "legendFormat": "{{port}}"
    },
    {
     "expr": "me5_controller_iops{host=\"$host\"} > 0",
     "legendFormat": "{{id}}"
    },
    {
     "expr": "me5_pool_iops{host=\"$host\"} > 0",
     "legendFormat": "Pool {{pool}}"
    }
   ]
  },
  { "title": "Pools and Volumes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "Pool Capacity",
   "type": "stat",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "me5_pool_size_bytes{host=\"$host\"}",
     "legendFormat": "Pool {{pool}} - Total Size"
    },
    {
     "expr": "me5_pool_available_bytes{host=\"$host\"}",
     "legendFormat": "Pool {{pool}} - Available"
    },
    {
     "expr": "me5_pool_size_bytes - me5_pool_available_bytes{host=\"$host\"}",
     "legendFormat": "Pool {{pool}} - Used"
    }
   ]
  },
  {
   "title": "Volume Breakdown",
   "type": "table",
   "gridPos": { "h": 5, "w": 9, "x": 9, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "me5_volume_size_bytes{host=\"$host\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "me5_volume_allocated_bytes{host=\"$host\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "me5_volume_iops{host=\"$host\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Disk Group ($disk_group)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 }, "repeat": "disk_group" },
  {
   "title": "Avg. Read Latency ($disk_group)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "me5_disk_group_avg_read_rsp_time_microseconds{name='$disk_group',host=\"$host\"} ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Avg. Write Latency ($disk_group)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "me5_disk_group_avg_write_rsp_time_microseconds{name='$disk_group',host=\"$host\"} ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk Group Throughput ($disk_group)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "me5_disk_group_bytes_per_second{name='$disk_group',host=\"$host\"} ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk Group IOPS ($disk_group)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "me5_disk_group_iops{name='$disk_group',host=\"$host\"} ",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": " Drives", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 } },
  {
   "title": "Average Disk Response Time",
   "type": "table",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "topk(90,last_over_time(me5_disk_average_response_time_microseconds{host=\"$host\"}[1h]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Drive Temperatures",
   "type": "table",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "topk(90, last_over_time(me5_disk_temperature_celsius{host=\"$host\"}[1h]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Drive Life Remaining",
   "type": "table",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "bottomk(90, last_over_time(me5_disk_ssd_life_left_percentage{host=\"$host\"}[1h]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Sensors and Fans", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 } },
  {
   "title": "Sensor Status",
   "type": "table",
   "gridPos": { "h": 15, "w": 9, "x": 0, "y": 51 },
   "targets": [
    {
     "expr": "me5_sensor_status{host=\"$host\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Fan Status",
   "type": "table",
   "gridPos": { "h": 15, "w": 9, "x": 9, "y": 51 },
   "targets": [
    {
     "expr": "me5_fan_status{host=\"$host\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}